version: '3.8'
services:
  stats-server:
    build: ./server
    container_name: wfy_server
    ports:
      - "8080:8080"
    depends_on:
      - wfy-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wfy-db:5432/wfy-db?encoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080

  wfy-db:
    image: postgres:15.1-alpine
    container_name: wfy-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=wfy-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data/
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql