CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255) UNIQUE                               NOT NULL,
    email VARCHAR(50)                                      NOT NULL
    );

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                NOT NULL
    );

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                NOT NULL,
    description VARCHAR(300)                               NOT NULL
    );

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50)                                        NOT NULL,
    latitude FLOAT                                          NOT NULL,
    longitude FLOAT                                         NOT NULL,
    radius BIGINT                                           NOT NULL
);

CREATE TABLE IF NOT EXISTS vacancies (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(50)                                        NOT NULL,
    description  VARCHAR(1000)                               NOT NULL,
    recruiter_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    state VARCHAR(50),
    views BIGINT DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE                 NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text  VARCHAR(1000)                                      NOT NULL,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES companies (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE                      NOT NULL
    );

CREATE TABLE IF NOT EXISTS resumes (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description  VARCHAR(1000)                               NOT NULL,
    creator_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE                   NOT NULL
    );

CREATE TABLE IF NOT EXISTS reactions (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    vacancy_id BIGINT REFERENCES vacancies (id) ON DELETE CASCADE,
    resume_id BIGINT REFERENCES resumes (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE                      NOT NULL
    );


